"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Sparkles, Loader2, FileText, DollarSign, Wand2 } from "lucide-react";
import { toast } from "sonner";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";

interface GenerateProposalModalProps {
  clientId: string;
  clientName: string;
  conversationId?: string;
  defaultBudget?: number;
  trigger?: React.ReactNode;
}

export function GenerateProposalModal({
  clientId,
  clientName,
  conversationId,
  defaultBudget,
  trigger,
}: GenerateProposalModalProps) {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [loading, setLoading] = useState(false);

  const [projectTitle, setProjectTitle] = useState("");
  const [rawConversation, setRawConversation] = useState("");
  const [budget, setBudget] = useState<string>(
    defaultBudget ? defaultBudget.toString() : ""
  );

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!projectTitle.trim()) {
      toast.error("Project title is required.");
      return;
    }

    if (!rawConversation.trim() || rawConversation.trim().length < 20) {
      toast.error("Meeting notes / chat transcript must be at least 20 characters long.");
      return;
    }

    setLoading(true);

    try {
      const res = await fetch("/api/proposals/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          clientId,
          conversationId: conversationId || null,
          projectTitle: projectTitle.trim(),
          rawConversation: rawConversation.trim(),
          budget: budget ? parseFloat(budget) : undefined,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        if (res.status === 429 || data.error?.includes("LIMIT_RESTRICTION")) {
          const cleanMessage = data.error.replace("LIMIT_RESTRICTION:", "").trim();
          
          toast.error(cleanMessage, {
            duration: 6000,
            icon: '🛑',
          });
          
          setLoading(false);
          return;
        }

        throw new Error(data.error || "Failed to generate proposal.");
      }

      toast.success("Proposal successfully generated by AI!");
      setOpen(false);
      router.push(`/projects/${data.projectId}/proposal`);

    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Unable to generate proposal.";
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {trigger || (
          <Button className="gap-2 font-semibold bg-gradient-to-r from-amber-500 to-primary text-white shadow-md hover:opacity-90 transition-opacity">
            <Sparkles className="h-4 w-4" /> Generate AI Proposal
          </Button>
        )}
      </DialogTrigger>

      <DialogContent className="sm:max-w-[550px]">
        <form onSubmit={handleGenerate}>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-xl">
              <Sparkles className="h-5 w-5 text-amber-500" />
              Generate Proposal for {clientName}
            </DialogTitle>
            <DialogDescription>
              Paste the client meeting notes or chat transcript below. The AI will generate a complete technical breakdown, tech stack, and commercial proposal.
            </DialogDescription>
          </DialogHeader>

          <div className="grid gap-4 py-4">
            {/* Project Title */}
            <div className="grid gap-2">
              <Label htmlFor="title" className="text-sm font-semibold">
                Project Title <span className="text-destructive">*</span>
              </Label>
              <Input
                id="title"
                placeholder="e.g., Hospital Management Portal & Mobile App"
                value={projectTitle}
                onChange={(e) => setProjectTitle(e.target.value)}
                disabled={loading}
                required
              />
            </div>

            {/* Budget (Optional Override) */}
            <div className="grid gap-2">
              <Label htmlFor="budget" className="text-sm font-semibold flex items-center justify-between">
                <span>Estimated Budget ($)</span>
                <span className="text-xs text-muted-foreground font-normal">Optional</span>
              </Label>
              <div className="relative">
                <DollarSign className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground" />
                <Input
                  id="budget"
                  type="number"
                  placeholder="e.g., 3500"
                  className="pl-9"
                  value={budget}
                  onChange={(e) => setBudget(e.target.value)}
                  disabled={loading}
                />
              </div>
            </div>

            {/* Raw Conversation / Scope */}
            <div className="grid gap-2">
              <Label htmlFor="requirements" className="text-sm font-semibold flex items-center gap-1.5">
                <FileText className="h-3.5 w-3.5 text-primary" />
                Client Meeting Notes / Transcript <span className="text-destructive">*</span>
              </Label>
              <Textarea
                id="requirements"
                rows={6}
                placeholder={`Paste client chat transcript, meeting notes, or raw requirements here...\n\nExample:\n- Client needs a patient booking portal with doctor slots\n- Stripe / JazzCash payment integration\n- Need fast turn-around in 4 weeks`}
                value={rawConversation}
                onChange={(e) => setRawConversation(e.target.value)}
                disabled={loading}
                required
                className="text-xs leading-relaxed font-mono"
              />
              <p className="text-[11px] text-muted-foreground">
                Providing more details enables the AI Solution Architect to generate a more accurate scope.
              </p>
            </div>
          </div>

          <DialogFooter className="gap-2 sm:gap-0">
            <Button
              type="button"
              variant="outline"
              onClick={() => setOpen(false)}
              disabled={loading}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={loading} className="gap-2">
              {loading ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin text-amber-400" />
                  Generating...
                </>
              ) : (
                <>
                  <Wand2 className="h-4 w-4" />
                  Generate Proposal
                </>
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}